import { Movie } from './types';

export const MOVIES: Movie[] = [
  {
    id: '1',
    title: 'Inception',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    genre: ['Sci-Fi', 'Action', 'Adventure'],
    releaseYear: 2010,
    rating: 8.8,
    duration: '2h 28m',
    language: 'English',
    posterUrl: 'https://picsum.photos/seed/inception/400/600',
    backdropUrl: 'https://picsum.photos/seed/inception-bg/1200/600',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
    director: 'Christopher Nolan'
  },
  {
    id: '2',
    title: 'The Dark Knight',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    genre: ['Action', 'Crime', 'Drama'],
    releaseYear: 2008,
    rating: 9.0,
    duration: '2h 32m',
    language: 'English',
    posterUrl: 'https://picsum.photos/seed/darkknight/400/600',
    backdropUrl: 'https://picsum.photos/seed/darkknight-bg/1200/600',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    director: 'Christopher Nolan'
  },
  {
    id: '3',
    title: 'Interstellar',
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    genre: ['Sci-Fi', 'Drama', 'Adventure'],
    releaseYear: 2014,
    rating: 8.7,
    duration: '2h 49m',
    language: 'English',
    posterUrl: 'https://picsum.photos/seed/interstellar/400/600',
    backdropUrl: 'https://picsum.photos/seed/interstellar-bg/1200/600',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    director: 'Christopher Nolan'
  },
  {
    id: '4',
    title: 'The Grand Budapest Hotel',
    description: 'A writer encounters the owner of a declining high-class hotel, who tells him of his early years serving as a lobby boy in the hotel\'s glorious years under an exceptional concierge.',
    genre: ['Comedy', 'Adventure', 'Crime'],
    releaseYear: 2014,
    rating: 8.1,
    duration: '1h 39m',
    language: 'English',
    posterUrl: 'https://picsum.photos/seed/budapest/400/600',
    backdropUrl: 'https://picsum.photos/seed/budapest-bg/1200/600',
    cast: ['Ralph Fiennes', 'F. Murray Abraham', 'Mathieu Amalric'],
    director: 'Wes Anderson'
  },
  {
    id: '5',
    title: 'Parasite',
    description: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    genre: ['Drama', 'Thriller', 'Comedy'],
    releaseYear: 2019,
    rating: 8.5,
    duration: '2h 12m',
    language: 'Korean',
    posterUrl: 'https://picsum.photos/seed/parasite/400/600',
    backdropUrl: 'https://picsum.photos/seed/parasite-bg/1200/600',
    cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'],
    director: 'Bong Joon-ho'
  },
  {
    id: '6',
    title: 'Spirited Away',
    description: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    genre: ['Animation', 'Adventure', 'Family'],
    releaseYear: 2001,
    rating: 8.6,
    duration: '2h 5m',
    language: 'Japanese',
    posterUrl: 'https://picsum.photos/seed/spirited/400/600',
    backdropUrl: 'https://picsum.photos/seed/spirited-bg/1200/600',
    cast: ['Daveigh Chase', 'Suzanne Pleshette', 'Jason Marsden'],
    director: 'Hayao Miyazaki'
  },
  {
    id: '7',
    title: 'The Shawshank Redemption',
    description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    genre: ['Drama'],
    releaseYear: 1994,
    rating: 9.3,
    duration: '2h 22m',
    language: 'English',
    posterUrl: 'https://picsum.photos/seed/shawshank/400/600',
    backdropUrl: 'https://picsum.photos/seed/shawshank-bg/1200/600',
    cast: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'],
    director: 'Frank Darabont'
  },
  {
    id: '8',
    title: 'Pulp Fiction',
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    genre: ['Crime', 'Drama'],
    releaseYear: 1994,
    rating: 8.9,
    duration: '2h 34m',
    language: 'English',
    posterUrl: 'https://picsum.photos/seed/pulpfiction/400/600',
    backdropUrl: 'https://picsum.photos/seed/pulpfiction-bg/1200/600',
    cast: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
    director: 'Quentin Tarantino'
  },
  {
    id: '9',
    title: 'The Matrix',
    description: 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.',
    genre: ['Action', 'Sci-Fi'],
    releaseYear: 1999,
    rating: 8.7,
    duration: '2h 16m',
    language: 'English',
    posterUrl: 'https://picsum.photos/seed/matrix/400/600',
    backdropUrl: 'https://picsum.photos/seed/matrix-bg/1200/600',
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
    director: 'Lana Wachowski'
  },
  {
    id: '10',
    title: 'The Godfather',
    description: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    genre: ['Crime', 'Drama'],
    releaseYear: 1972,
    rating: 9.2,
    duration: '2h 55m',
    language: 'English',
    posterUrl: 'https://picsum.photos/seed/godfather/400/600',
    backdropUrl: 'https://picsum.photos/seed/godfather-bg/1200/600',
    cast: ['Marlon Brando', 'Al Pacino', 'James Caan'],
    director: 'Francis Ford Coppola'
  },
  {
    id: '11',
    title: 'The Silence of the Lambs',
    description: 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.',
    genre: ['Crime', 'Drama', 'Thriller'],
    releaseYear: 1991,
    rating: 8.6,
    duration: '1h 58m',
    language: 'English',
    posterUrl: 'https://picsum.photos/seed/silence/400/600',
    backdropUrl: 'https://picsum.photos/seed/silence-bg/1200/600',
    cast: ['Jodie Foster', 'Anthony Hopkins', 'Lawrence A. Bonney'],
    director: 'Jonathan Demme'
  },
  {
    id: '12',
    title: 'Gladiator',
    description: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
    genre: ['Action', 'Adventure', 'Drama'],
    releaseYear: 2000,
    rating: 8.5,
    duration: '2h 35m',
    language: 'English',
    posterUrl: 'https://picsum.photos/seed/gladiator/400/600',
    backdropUrl: 'https://picsum.photos/seed/gladiator-bg/1200/600',
    cast: ['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen'],
    director: 'Ridley Scott'
  },
  {
    id: '13',
    title: 'The Lion King',
    description: 'Lion prince Simba and his father are targeted by his treacherous uncle, who wants to ascend the throne himself.',
    genre: ['Animation', 'Adventure', 'Drama'],
    releaseYear: 1994,
    rating: 8.5,
    duration: '1h 28m',
    language: 'English',
    posterUrl: 'https://picsum.photos/seed/lionking/400/600',
    backdropUrl: 'https://picsum.photos/seed/lionking-bg/1200/600',
    cast: ['Matthew Broderick', 'Jeremy Irons', 'James Earl Jones'],
    director: 'Roger Allers'
  },
  {
    id: '14',
    title: 'Se7en',
    description: 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.',
    genre: ['Crime', 'Drama', 'Mystery'],
    releaseYear: 1995,
    rating: 8.6,
    duration: '2h 7m',
    language: 'English',
    posterUrl: 'https://picsum.photos/seed/seven/400/600',
    backdropUrl: 'https://picsum.photos/seed/seven-bg/1200/600',
    cast: ['Morgan Freeman', 'Brad Pitt', 'Kevin Spacey'],
    director: 'David Fincher'
  },
  {
    id: '15',
    title: 'The Prestige',
    description: 'After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.',
    genre: ['Drama', 'Mystery', 'Sci-Fi'],
    releaseYear: 2006,
    rating: 8.5,
    duration: '2h 10m',
    language: 'English',
    posterUrl: 'https://picsum.photos/seed/prestige/400/600',
    backdropUrl: 'https://picsum.photos/seed/prestige-bg/1200/600',
    cast: ['Christian Bale', 'Hugh Jackman', 'Scarlett Johansson'],
    director: 'Christopher Nolan'
  }
];

export const GENRES = [
  'Action', 'Comedy', 'Drama', 'Romance', 'Thriller', 'Horror', 'Sci-Fi', 
  'Fantasy', 'Animation', 'Adventure', 'Crime', 'Mystery', 'Family', 
  'Biography', 'Documentary'
];
